<?php

namespace Ing200086\Reto\Tests\Feature;

use Ing200086\Reto\Graph;
use Ing200086\Reto\Edge\NewEdge;
use PHPUnit\Framework\TestCase;

class GraphEdgeTest extends TestCase {
    protected $graph;

    /** @test*/
    public function it_can_have_an_edge_created_between_two_vertices() {
        $this->graph->define(NewEdge::Undirected('a', 'b'));
        $this->graph->define(NewEdge::ToFrom('b', 'c'));
        $this->graph->define(NewEdge::FromTo('a', 'c'));

        $this->assertEquals(3, count($this->graph->edges()));
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->graph = Graph::FromJson($this->config());
    }

    public function config()
    {
        return [
            'vertices' => ['a', 'b', 'c']
        ];
    }
}
